### PR TITLE
Various minor changes 2020 05 27

### PR DESCRIPTION
**Pull request by maomeara63**
_Minor grammar and punctuation changes to 8 FAQs

image
_

Please confirm the following steps are completed:

* [x] Choose the appropriate target branch:
  * Content
    * `preview` (approved content) <- *Content branch*
    * `master` (production) <- `preview`
* [X] Assign an appropriate reviewer:
  * *Content admin* or *Project lead* for merge to `preview` (approved content)
  * *Engineer* for merge to master (production)

:sunglasses:
(<https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/various-minor-changes-2020-05-27/retirement-communities/how-can-my-retirement-community-or-independent-living-facility-prepare/>)

(<https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/various-minor-changes-2020-05-27/travel/what-can-i-expect-when-arriving-to-the-united-states/>)

(<https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/various-minor-changes-2020-05-27/protect-yourself/can-cdc-tell-me-when-it-is-safe-to-go-back/>)

(<https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/various-minor-changes-2020-05-27/protect-yourself/should-i-go-to-work-if-there-is-an-outbreak-in-my-community/>)

(<https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/various-minor-changes-2020-05-27/keeping-home-safe/if-someone-in-my-house-gets-sick/>)

(<https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/various-minor-changes-2020-05-27/financial-help/is-the-government-delaying-tax-day/>)

(<https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/various-minor-changes-2020-05-27/spread/how-does-the-virus-spread/>)

(<https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/various-minor-changes-2020-05-27/travel/can-american-citizen-return-to-us/>)

### CODE REVIEW

**Comment by janeopm** [comment]
These look ok except on the How Does the virus spread page: Replace concluding sentence with: 
Learn what is known about the spread of ~newly emerged coronavirus~COVID-19.

(there are many coronaviruses, (SARS, MERS, and many others) feel like we should just point to the one we are dealing with.) Would like Misty to review this FAQ before we push it to prod. The others are good to go.

**Comment by debjudy** [comment]
Emails sent to partners for approval for the 2 questions.

**Comment by debjudy** [comment]
Received agency approval for american-citizen-return-to-us.

**Comment by maomeara63** [comment]
Received approval for how-does-the-virus-spread. @janeopm , please review and approve.

**Comment by janeopm** [comment]
approving this, but I cannot see the button to approve. Maybe because I self assigned this?

**Pull request merged**
