### PR TITLE
Added two animal Qs, edited 1

### PR DESCRIPTION
**Pull request by jonadecker**
Issue #575 

Added new questions: wild animals and bats, revised question about cats.

[Preview link](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/cdc-animal-4-24/animals/)

### CODE REVIEW

**Comment by vbitzer** [comment]
@jonadecker circleci fails 😱

**Comment by jonadecker** [comment]
Not sure why the circle-ci test failed here @hbillings. Commit is there but it didn't build on preview?

**Comment by jonadecker** [comment]
@vbitzer two questions (one add, one edit) are good. The bat question doesn't appear in the preview.

**Comment by Mtcarp** [comment]
@vbitzer Reviewed this one again and looks like all issues have been resolved. It's ready to merge. Once done, we can move to production so I can share a link to the live site with our contact. 
cc: @hbillings

**Pull request merged**
