### PR TITLE
Updates CDC FAQs

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Updates the following FAQs:

- What should I do if a family member dies of COVID-19 while overseas? [Preview](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/cdc-5-6/funerals/if-someone-dies-overseas/)
- Can the virus that causes COVID-19 be spread through food? [Preview](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/cdc-5-6/spread/can-the-virus-that-causes-covid-19-be-spread-through-food/)
- Should I travel within the United States? [Preview](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/cdc-5-6/travel/should-i-travel-within-the-us/)

_Note_: The last of these was converted (by CDC) from an FAQ to a stand-alone page. My update includes much of the page's content, and then links back to the CDC page for more. There's good information here, but the full page is too much for our format (there may still be too much in this version).

_Update 5/14 (JD)_: Shortened travel question to reflect Jane's copy below, for client approval.

### CODE REVIEW

**Comment by vbitzer** [comment]
@brentryanjohnson thanks for the warning. Yes, this content is quite long and kinda goes against what we've been telling agencies about quick, direct answers. Open to suggestions @janeopm and how you see this moving forward.

**Comment by jonadecker** [comment]
Could we keep the first paragraph, craft a transitional sentence and drive/link to the full content on CDC @janeopm @vbitzer ?

**Comment by janeopm** [comment]
First 2 look fine. But PerJona's suggestion how about keeping the first paragraph and linking to  [state or local authorities](https://www.cdc.gov/publichealthgateway/healthdirectories/healthdepartments.html) to this CDC page: https://www.cdc.gov/publichealthgateway/healthdirectories/healthdepartments.html

**Comment by jonadecker** [comment]
Edited "Should I travel within US" FAQ to reflect Jane's edits. Adding Preview Links to each question above for sharing with task force liaison for approval.

**Comment by janeopm** [comment]
approved to push to production! per Misty

**Pull request merged**
