### PR TITLE
Add JSON endpoints for syndication

### PR DESCRIPTION
**Pull request by ExMember**
Add a JSON API for syndication.

Related: https://github.com/18F/cv_faq/issues/404,  https://github.com/18F/cv_faq/issues/510

# How to use the API

The API consists of two endpoints that serve JSON. One contains the complete list of categories. The other contains the complete list of answers.

PR #510 adds the [API specification](https://editor.swagger.io/?url=https://raw.githubusercontent.com/18F/cv_faq/add-openapi-spec/api/openapi.yaml)

# Future work

## Automated testing

Automated tests can ensure the endpoints return valid JSON, in the documented structure, and with the correct data.

## Contributors

[Damien Burke](https://github.com/exmember)

[Rob Head](https://github.com/roberthead)

### Special thanks

[Megan Folsom](https://github.com/mfolsom)

[Jordan Epps](https://github.com/jkepps)

[Justin Man](https://github.com/jisaf)

[NYC Mayor's Office of the Chief Technology Officer](https://www1.nyc.gov/assets/cto/)

[Talaria Software](https://www.talariasoftware.com)

### CODE REVIEW

**Comment by adunkman** [comment]
Thanks so much for the contribution, @ExMember! 

> excerpt: the category name. Human-readable text. This data is not displayed on the Coronavirus FAQ page and it is recommended that you ignore it.

We should probably delete this… 🤔 let me poke around a bit and see what that would take. 

I have a concern about potential upcoming changes — #318 is likely to change the `promoted` attribute, and I get 😬 when APIs change. 

I’m thinking about a slimmed-down version of these objects, with the keys that are more set in stone — the source data, the questions, answers, category names… those sorts of things.

**Comment by thomhalla** [comment]
yes @adunkman , json endpoint with docs achieves the goal!

**Comment by ExMember** [comment]
That sounds very reasonable @adunkman. We took a kitchen-sink approach because we didn't know what was necessary and what was stable.

Here's my guess at what's necessary and stable:

Answers:
- title
- category
- content
- date
- url
- source
- source_url

Categories:
- title
- url
- banner (heading and content)

Give me confirmation of that and I'll make the changes.

**Comment by philipashlock** [comment]
It might be worth considering consolidating this with the schema.org version of the JSON feed (see #393) since there's now [national guidance](https://www.whitehouse.gov/articles/connecting-americans-coronavirus-information-online/) to syndicate COVID-19 info throughout Federal/State/Local sources with Schema.org specs, preferably the [COVID-19 specific ones](http://blog.schema.org/2020/03%E2%80%8B/schema%E2%80%8B-for%E2%80%8B-coronavirus%E2%80%8B-special%E2%80%8B.html). So it might also be worth looking into the applicability of those new specs in addition to standard ones like [FAQpage](https://schema.org/FAQPage). 

see also:

- https://blogs.bing.com/webmaster/march​-2020​/Bing​-adopts​-schema​-org​-mark​-up​-for​-Special​-Announcements​-about​-COVID​-19
- https://webmasters.googleblog.com/2020/04​/highlight​-covid​-19​-announcements​-search​.html
- https://support.google.com/webmasters/answer​/9781983

**Comment by adunkman** [comment]
I agree that it’s important to continue to iterate on Schema.org, and I also agree that we should be providing this content additionally in an API format for syndication. 

@philipashlock Would you be able to create a new issue with your requested changes? It might be the most efficient if you do so, as I haven’t read up on the provided info (and it sounds like you have — awesome!). 

@ExMember I’m spending a few minutes thinking this through, and will provide guidance soon. Thanks!

**Comment by philipashlock** [comment]
@adunkman Agreed and yeah, no problem. I'll get something in later today.

**Comment by adunkman** [comment]
- I informally polled some colleagues, and the consensus that FAQ items are a `question` rather than an `answer`, so let’s use `questions.json` over `answers.json` unless you have a strong objection. 

- Some questions have more than one source, although they’re currently [poorly implemented as `source_2` and `source_url_2`](https://github.com/18F/cv_faq/blob/cba7eba49c7e9606be76fee84d371c19cb18bfad/_content/rumors/should-i-worry-about-hantavirus.md). Let’s hide our dirty implementation secret and use an array for these in the JSON endpoint. 

- If we include the answer text as well as the html, we can follow-up to this change and [remove our search.json endpoint](https://github.com/18F/cv_faq/blob/e66cd6eb2e1b4e8c1a0a2456577ebe1e40b6aae0/search.json). I suspect other consumers will find the text format useful as well.


### /api/v1/questions.json

```json
[
  {
    "question_url": "string",
    "title": "string",
    "answer": "string",
    "answer_html": "string",
    "updated_at": "2020-04-15",
    "category": {
      "title": "string",
      "category_url": "string"
    },
    "sources": [
      {
        "name": "string",
        "source_url": "string"
      }
    ]
  }
]
```

### /api/v1/categories.json

```json
[
  {
    "category_url": "string",
    "title": "string"
  }
]
```

How does this sound, @ExMember? I’ll open a pull request to add a OpenAPI specification for these endpoints as well.

**Comment by ExMember** [comment]
I think `answer` is a much better name, but it's more important to use the name you use internally.

I'll make those changes now.

**Pull request merged**
