### PR TITLE
Re-categorization

### PR DESCRIPTION
**Pull request by debjudy**
Branch for changes related to updated categories

Please confirm the following steps are completed:

* [x] Choose the appropriate target branch:
  * Content
    * `preview` (approved content) <- *Content branch*
    * `main` (production) <- `preview`
* [x] Assign an appropriate reviewer:
  * *Content admin* or *Project lead* for merge to `preview` (approved content)
  * *Engineer* for merge to master (production)

:sunglasses: [PREVIEW URL]()

### CODE REVIEW

**Comment by debjudy** [comment]
Reviewed and closed schools meals #1079, pregnancy #1076 and small business support #1080

**Comment by debjudy** [comment]
Reviewed and closed 
- workplace-safety #1046 
- disinfecting-sanitizing #1070 
- treatments-vaccines-immunity #1087 
- pets-animals #1075 
- spread-transmission #1081 
- older-people-special-precautions #1074 
- activities-events-gatherings #1067

**Comment by debjudy** [comment]
reviewed and closed related issues 

- caring for children #1068 
- prevent getting sick #1078 
- financial help #1071 
- food, housing and education assistance #1073 
- travel #1083 
- food and drug safety #1072 
- covid-19 facts #1069 
- symptoms and testing #1082

**Review by maomeara63 — COMMENTED** [review]
Looks good to go.

**Review by maomeara63 — APPROVED** [review]
Looks good to go.

**Pull request merged**
