### PR TITLE
Adds USDA FAQs (Ready for Publish)

### PR DESCRIPTION
**Pull request by Mtcarp**
### Updates include:
- Adds new agency markdown file: usda
- Adds new category markdown file: food-safety
- Duplicate question not added:"Can I become sick with COVID-19 from food?" (**Reason:** Already have a similar FDA FAQ and different USDA FAQ, "Are meat products compromised by COVID-19?" has same answer)

### Questions added to the following categories:

See all new USDA FAQ using [PREVIEW LINK](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/agency/usda/) of USDA Agency Landing Page.

#### Food access and safety (3 USDA) - [PREVIEW LINK of new category](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/food-safety/)
- Are meat products compromised by COVID-19?
- Is there guidance on food planning for families during the coronavirus pandemic? 
- Where can I find out more information about nutrition assistance available during the national emergency? 

#### Financial help (3 USDA)
- [If my financial situation has changed due to the coronavirus, could I be eligible for SNAP?](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/financial-help/if-my-financial-situation-changed-could-i-be-eligible-for-snap/)
- [Can SNAP participants order groceries online?](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/financial-help/can-snap-participants-order-groceries-online/)

#### Parents and children (6 USDA)
- [Can schools still serve meals while they are closed?](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/parents-and-children/can-schools-serve-meals-while-they-are-closed/)
- [Can schools provide home delivery of meals?](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/parents-and-children/can-schools-provide-home-delivery-of-meals/)
- [Can parents pick-up meals for their kids without their children present?](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/parents-and-children/can-parents-pick-up-meals-for-their-kids-without-them-present/)
- [Can schools provide multiple meals at once?](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/parents-and-children/can-schools-provide-multiple-meals-at-once/)
- [Do school meals still have to meet the nutrition requirements?](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/parents-and-children/do-school-meals-still-have-to-meet-nutrition-requirements/)

### Questions NOT INCLUDED in this PR because of editorial recommendations (that were not made but should be suggested):

**Two questions under "How to protect yourself":**
- [Will National Forest recreation sites and facilities stay open? ](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/protect-yourself/will-national-forest-recreation-sites-stay-open/)
- [What can the public do to practice social distancing while recreating on National Forest System lands?](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/protect-yourself/what-can-the-public-do-to-practice-social-distancing-while-visiting-national-forest-system-lands/)

**Not added because we are suggesting to combine into a single FAQ** - "Can the public still visit National Forest recreation sites and facilities? If so, how can they do safely?"

**One question under "Financial help":**
- [What happens to SNAP recipients who can’t meet the work requirements due to the coronavirus outbreak?](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/financial-help/what-happens-to-snap-recipients-who-cannot-meet-work-requirements-due-to-covid19/)

**Not added because we are suggesting to remove the link to PDF** under this question since it is an email addressed to all state agency directors and not the general public.

**One question under "Parent and children":**
- [What action is being taken to ensure children have food to eat while schools are closed?](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/parents-and-children/what-actions-is-being-taken-to-ensure-children-have-food-while-school-is-closed/)

**Not added because we are suggesting to edit the first sentence of last paragraph as follows:** “The Families First Coronavirus Response Act also provides states **with** the option to provide EBT benefits…”

### CODE REVIEW

**Comment by vbitzer** [comment]
Can we change this: "What can the public do to practice social distancing while recreating on National Forest System lands?" to What can the public do to practice social distancing while visiting National Forest System lands?

**Comment by Mtcarp** [comment]
@vbitzer This is ready for your review. Please see the USDA content. Preview links are included above.
cc: @lauraGgit There was a CircleCI fail on one of my commits but overall the PR successfully met all checks.

**Comment by Mtcarp** [comment]
@vbitzer Per our conversation during afternoon huddle, this PR only includes the USDA content that is ready to publish. Noted in the description of the PR are the 4 questions that are not added because of editorial recommendations.

**Comment by Mtcarp** [comment]
@vbitzer Here is the preview link of the content that is ready to move to production: https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-content-4-27/agency/usda/

**Comment by Mtcarp** [comment]
@lauraGgit Content on this PR is ready to move to production and publish on live site. Please share the url link once published. Thanks!
cc: @danielnaab @piascikj

**Pull request merged**
