### PR TITLE
Upgrade USWDS from 2.1 to 2.7.1

### PR DESCRIPTION
**Pull request by danielnaab**
Upgrade to USWDS 2.7.1 and make a few tweaks to maintain design consistency.

Please confirm the following steps are completed:

* [x] Choose the appropriate target branch:
  * Content
    * `preview` (approved content) <- *Content branch*
    * `master` (production) <- `preview`
* [x] Assign an appropriate reviewer:
  * *Content admin* or *Project lead* for merge to `preview` (approved content)
  * *Engineer* for merge to master (production)

:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/upgrade-uswds/)

### CODE REVIEW

**Comment by jonadecker** [comment]
I can't tell when you added the "ignore" note so I'll just mention you've got some bottom half of home page issues:

Screen Shot 2020-07-02 at 2 48 10 PM

**Comment by debjudy** [comment]
Seeing same issue on homepage as Jona on Edge browser.  Happily (surprisingly) no additional issues on Edge. .

**Comment by danielnaab** [comment]
@jonadecker @debjudy I added you all a bit early, only after testing the wrong build locally (doh). Thanks for bug note, I should be able to fix by Monday. There were fewer upgrade issues than I expected!

**Comment by danielnaab** [comment]
This is good to test now - there are some slight padding changes with 2.7, but otherwise the visuals should be consistent with current production.

**Pull request merged**
